name: Build development client
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [16.x]

    steps:
    - name: 🏗 Setup repo
      uses: actions/checkout@v2

    - name: 🏗 Setup Node
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node }}
        #cache: yarn

    - name: 🏗 Setup Expo and EAS
      uses: expo/expo-github-action@v7
      with:
        token: ${{ secrets.EXPO_TOKEN }}
        expo-version: latest
        eas-version: latest

    - name: 🏗 Setup EAS local builds
      run: yarn global add eas-cli-local-build-plugin

    - name: 📦 Install dependencies
      run: yarn

    #- name: 📋 Test project
    #  run: yarn test

    - name: 👷 Build app
      run: |
        eas build --local \
          --non-interactive \
          --output=./build \
          --platform=android \
          --profile=development

    - name: 📱 Upload binary
      uses: actions/upload-artifact@v2
      with:
        name: android
        path: build
      
