name: Build development client
on: push
#on:
  #pull_request:
    #types:
      #- closed
    #branches:
      #- main

jobs:
  main:
    runs-on: ubuntu-20.04

    steps:
    - name: 🏗 Check out repo
      uses: actions/checkout@v3

    - name: ✍ Update version number
      run: |
        YEAR=$(date +"%Y")
        MONTH=$(date +"%m")
        VERSION="$YEAR.$MONTH.$GITHUB_RUN_NUMBER-dev"
        sed -i "s/\"version\": \".*\"/\"version\": \"$VERSION\"/" package.json
        sed -i "s/\"version\": \".*\"/\"version\": \"$VERSION\"/" app.json
        echo "Changed version to $VERSION in package.json and app.json"

    - name: ⚙ Install Node
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: ⚙ Install Java
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: 17

    - name: ⚙ Install Android SDK
      uses: android-actions/setup-android@v2

    - name: ⚙ Install Expo and EAS
      uses: expo/expo-github-action@v7
      with:
        token: ${{ secrets.EXPO_TOKEN }}
        expo-version: latest
        eas-version: latest

    - name: ⚙ Install EAS local builds
      run: yarn global add eas-cli-local-build-plugin

    - name: ⚙ Install dependencies
      run: yarn install

    - name: 👷 Build app
      run: |
        eas build --local \
          --non-interactive \
          --output="build/app-debug.apk" \
          --platform=android \
          --profile=development

    - name: 📦 Upload binary
      uses: actions/upload-artifact@v3
      with:
        name: Android Development Build
        path: build
        retention-days: 30
