name: Build development client
on: push
#on:
  #pull_request:
    #types:
      #- closed
    #branches:
      #- main

env:
  NAME: Jelly Mobile

jobs:
  main:
    runs-on: ubuntu-20.04

    steps:
    - name: 🏗 Check out repo
      uses: actions/checkout@v3

    - name: ✍ Update version number
      run: |
        sed -i "s/\"version\": \".*\"/\"version\": \"$(date +"%Y").$(date +"%m").${{ GITHUB_RUN_NUMBER }}\"/" package.json
        sed -i "s/\"version\": \".*\"/\"version\": \"$(date +"%Y").$(date +"%m").${{ GITHUB_RUN_NUMBER }}\"/" app.json
        echo "Changed version to $(date +"%Y").$(date +"%m").${{ GITHUB_RUN_NUMBER }} in package.json and app.json"
        echo "${{ env.NAME }}"

    - name: ⚙ Install Node
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: ⚙ Install Java
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: 17

    - name: ⚙ Install Android SDK
      uses: android-actions/setup-android@v2

    - name: ⚙ Install Expo and EAS
      uses: expo/expo-github-action@v7
      with:
        token: ${{ secrets.EXPO_TOKEN }}
        expo-version: latest
        eas-version: latest

    - name: ⚙ Install EAS local builds plugin
      run: yarn global add eas-cli-local-build-plugin

    - name: 👷 Build app
      run: |
        eas build --local \
          --non-interactive \
          --output="build/debug.apk" \
          --platform=android \
          --profile=development

    - name: ✈ Upload binary
      uses: actions/upload-artifact@v3
      with:
        name: Android Development Build
        path: build
        retention-days: 30
