name: Build development client
on: push
#on:
  #pull_request:
    #types:
      #- closed
    #branches:
      #- main

env:
  NAME: Jelly Mobile
  VERSION: $(date +"%Y").$(date +"%m").${{ GITHUB_RUN_NUMBER }}

jobs:
  main:
    runs-on: ubuntu-20.04

    steps:
    - name: 🏗 Setup repo
      uses: actions/checkout@v3

    - name: ✍ Update version number
      run: |
        sed -i "s/\"version\": \".*\"/\"version\": \"${{ env.VERSION }}\"/" package.json
        sed -i "s/\"version\": \".*\"/\"version\": \"${{ env.VERSION }}\"/" app.json
        echo "Changed version to ${{ env.VERSION }} in package.json and app.json"

    - name: 🏗 Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: 🏗 Setup Java
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: 17

    - name: 🏗 Setup Android SDK
      uses: android-actions/setup-android@v2

    - name: 🏗 Setup Expo and EAS
      uses: expo/expo-github-action@v7
      with:
        token: ${{ secrets.EXPO_TOKEN }}
        expo-version: latest
        eas-version: latest

    - name: 🏗 Setup EAS local builds
      run: yarn global add eas-cli-local-build-plugin

    - name: 👷 Build app
      run: |
        eas build --local \
          --non-interactive \
          --output=. \
          #--output="build/${{ env.NAME }} ${{ env.VERSION }}" \
          --platform=android \
          --profile=development

    #- name: ✈ Upload binary
    #  uses: actions/upload-artifact@v3
    #  with:
    #    name: Android Development Build
    #    path: "build/${{ env.NAME }} ${{ env.VERSION }}"
    #    retention-days: 30
      
